inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/EndOfLine:
  Enabled: False

Metrics/BlockLength:
  Enabled: False

Metrics/MethodLength:
  Enabled: False

Style/AccessModifierDeclarations:
  Enabled: False

Metrics/AbcSize:
  Enabled: False

Style/GuardClause:
  Enabled: False
